name: Build and Deploy Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab on Repo homepage
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest   
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.4
        # Don't forget to add environment vars as secrets in repository settings on GitHub
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # SSH port
          port: 22
          debug: true
          script: sh ~/Backend-Final/docker/deployment.sh prod

            # cd docker
            # echo "Shutting down current apps...."
            # docker-compose -f docker-compose.prod.yml down
            # docker-compose -f docker-compose.yml down
            # echo "Deleting images...."
            # docker system prune --all --force
            # echo "Building apps...."
            # docker-compose -f docker-compose.prod.yml build
            # echo "Starting database and app now...."
            # docker-compose -f docker-compose.prod.yml up -d
            # echo "Started database and app."

